### ISSUE TITLE
Adding Widget Causes Crash

### ISSUE THREAD

**Issue by shaydin** [NeoApplications/Neo-Launcher#185]
## Description
When adding any widget from Today Weather to a page, Neo Launcher immediately crashes. The widgets have a customize screen in between dragging them to the page and the widget's creation. After either selecting options in the customization window or leaving them as default and tapping Create, there is a brief second where the widget is visible, then animates away, then the launcher crashes and resets. 

This happens with any of the app's widgets, which are of varying sizes and display different info. I have granted all permissions requested to the launcher. I haven't seen these issues with Smart Launcher or Nova Launcher.

## Expected Behavior
After customizing the widgets and tapping Create, the widget should display as desired.

## Actual Behavior
After tapping Create, the homepage crashes, resets, and removes the widget that was just created.

## Steps to Reproduce

Install app: Today Weather
Long press on the homepage
Select Widgets
Scroll to and expand Today Weather
Drag any widget to the home page
Customize or leave the defaults and tap Create
Crash

## Device and OS

* Device: Samsung Galaxy S20 Ultra
* Android version: 12
* Launcher version: 0.9.0
* Rom: Stock, One UI 4.1

**Comment by jahasjahas** [comment]
Does this happen when you're trying to place the widget on a page that doesn't have enough space for it? Or always?

**Comment by shaydin** [comment]
> Does this happen when you're trying to place the widget on a page that doesn't have enough space for it? Or always?

Well, it was always happening no matter what was on the page. I tried multiple widgets from Today Weather and multiple items like shortcuts and widgets on the page (including no items). But I just went back to try again and now it's working. Neither app has updated, and I didn't change any settings between reporting this and now. The only thing I did was empty the page again, but as I mentioned, I'd tried that before with no luck. Super weird.

**Comment by shaydin** [comment]
I got it to work by removing everything from the home page and starting with the Today Weather widget that needed to be customized before it could be created. I then added a widget from a+ Calendar and that also worked fine, but needed no customizing. After trying a few more widgets it seems that adding more than one widget that needs to be customized before it can be created is causing a crash. 

I'm not sure if that's the original issue or just related, since I tried before with only the same calendar widget mentioned above and it still crashed, but that widget was there before I tried adding the Today Weather one that crashed Neo.

**Comment by FlareHeart** [comment]
I cannot add a widget from my Weather CAN app (Canadian weather) either. It also requires customization, but it was the first widget I tried to add and it crashes the launcher every time I try.

**Comment by machiav3lli** [comment]
It'd help to provide crashlogs. You can either do that with [Scoop](https://f-droid.org/en/packages/taco.scoop/) (needs root), [Matlog](https://f-droid.org/en/packages/com.pluscubed.matloglibre/) (usable with adb), or your preferred method…

**Comment by FlareHeart** [comment]
Well I'm not really a developer so I don't have a preferred method. I don't know how or where to retrieve the crash log for you (I would if I did).

**Comment by shaydin** [comment]
@machiav3lli  Sorry, got unbelievably busy and was unable to find time to get the crash to happen again in a timely manner. Got it to occur again by just trying to add a Hue widget to the home screen. Nothing complicated, just a single button static widget. Log file attached. Let me know if I need to add any filtering or widen/restrict the log level. 

[2022-09-02-23-02-24.txt](https://github.com/NeoApplications/Neo-Launcher/files/9481783/2022-09-02-23-02-24.txt)

**Comment by 2br-2b** [comment]
> Does this happen when you're trying to place the widget on a page that doesn't have enough space for it? Or always?

I have this exact issue - the launcher crashes if I try to add a widget to a page that doesn't have enough space. I can still add widgets on pages with enough space.

**Comment by MintMain21** [comment]
Yeah, trying to place a widget where there is no perceived space causes the launcher to crash. For me, on a device that isn't rooted and has the default launcher still installed, this basically forces me back to the default launcher and requires me to set the Neo Launcher as my default again.

Ideally, if there's no room for the widget, the launcher shouldn't bother to try and place the widget, and shouldn't crash trying to process it.

Slightly related also, I've had difficulty trying to remove larger widgets because of how small the "remove" space is, combining with the aforementioned crash bug to boot me back to the default launcher.

**Comment by saulhdev** [comment]
This issue has been resolved when rebasing to Android 13

**Comment by arpitjsolulab** [comment]
Can you please let me know the specific commit?

**Comment by Cyanide-1** [comment]
i still have this issue, adding any widget that needs customization crashes it

**Comment by battlezone** [comment]
I'm still encountering the issue. I could add RealCalc widget that doesn't need customization but can't add any (Breezy) weather or any calander widget, they need customization. I have enough space available, it just always crashes.
