### ISSUE TITLE
App icons disappear over time

### ISSUE THREAD

**Issue by ayesc9000** [NeoApplications/Neo-Launcher#220]
After using the launcher for a day or so, app icons begin to disappear and are instead replaced with a template icon. I have not been able to find a work around that does not involve uninstalling the app or completely resetting the launcher.

![Screenshot_20220810-021259.png](https://user-images.githubusercontent.com/29239155/183828616-9a09f6dc-473e-493b-b836-0db791c47c83.png)

This issue seems to mainly occur with apps that have full size icons, and not legacy smaller icons. Not all apps lose their icons at once. Instead, it seems to happen at random for some apps.

----

Version 0.9.1
Build 925
Package com.saggitt.omega
Downloaded from F-Droid

Google Pixel 5
Android 13 beta 4
Build TPB4.220624.008

**Comment by erazemk** [comment]
+1 for the issue, seems to happen after updating apps.

@ayesc9000 You can temporarily fix this for each app by holding it and in the customize menu clicking the app icon, then in the top right the smaller app icon.

![Screenshot_20220810-100126_Neo Launcher_1](https://user-images.githubusercontent.com/46302511/183848470-9c2bb153-d5de-4bc4-a8d9-11818973e220.png)

**Comment by machiav3lli** [comment]
It happens if you choose a custom app shape and is already fixed for next release.

**Comment by ayesc9000** [comment]
> It happens if you choose a custom app shape and is already fixed for next release.

0.9.2 did not fix the issue. Icons went back to normal for a bit but they are disappearing again.

**Comment by machiav3lli** [comment]
Yes, we're already aware of this and did couple of patches, we'll test for longer time then do a release should everything go well.

**Comment by saulhdev** [comment]
Secon try to fix it. I looks like it works. Commit b1161332

**Comment by ayesc9000** [comment]
Cool. I'll wait for this to go up on F-Droid and follow up if the fix works.
